### ISSUE TITLE
本地启动npm run start 出错

### ISSUE THREAD

**Issue by chinalijinglun** [wepayui/wepayui#4]
本地启动npm run start 出错，npm版本在3.10.10，node版本在6.9.0。

执行的时候报：

 Using gulpfile E:\wepayui-master\wepayui-master\gulpfile.js
 Task 'default' is not in your gulpfile
 Please check the documentation for proper gulpfile formatting

**Comment by ljinglun** [comment]
抱歉，已解决。

**Comment by ljinglun** [comment]
抱歉，已解决。
